[build]
target = "index.html"
dist = "dist"
public_url = "/"

[serve]
addr = "0.0.0.0"
port = 9090
open = false
no_autoreload = false

[clean]
dist = "dist"
cargo = false

[tools]
sass = "1.43.5"
wasm_bindgen = "0.2.78"
